/* eslint-disable */
enum EventName
{
    LOADING_IS_COMPLETE = "LOADING_IS_COMPLETE",
    CLOSE_WIN_SCREEN = "CLOSE_WIN_SCREEN",
    ROULETTE_STOPPED = "ROULETTE_STOPPED",
    ROULETTE_START = "ROULETTE_START",
    SCENE_LOADED = "SCENE_LOADED",
    MODEL_LOADED = "MODEL_LOADED",
    CHEST_OPENED = "CHEST_OPENED",
    CHEST_OPEN = "CHEST_OPEN",
}

export default EventName